### ISSUE TITLE
Template cover commands

### ISSUE THREAD

**Issue by ASchneiderBR** [hassio-addons/addon-homebridge#38]
## Problem/Motivation

Cover commands issue by the Home App does not work with template covers without current position sensor on HA. Also, optimistic mode is on. Example: "dumb" tubular motors controlled by RF 433 radio.

## Expected behavior

When cover is set to open on Home App, the command set on configuration.yaml open_cover is fired. This applies to close as well.

## Actual behavior

Nothing happens, the cover does not respond. I found workaround that is to set this config:
```
cover:
  - platform: template
    covers:
      persiana_suite:
        optimistic: true
        friendly_name: "Persiana da suíte"
        set_cover_position:
          service_template: >
            {% if is_state('cover.persiana_suite', 'open') %}
              script.persiana_suite_fechar
            {% elif is_state('cover.persiana_suite', 'closed') %}
              script.persiana_suite_abrir
            {% endif %}
        stop_cover:
          service: script.persiana_suite_parar
        open_cover:
          service: script.persiana_suite_abrir
        close_cover:
          service: sscript.persiana_suite_fechar
```
This works but scenes on Home App does not. Example: if I create a scene and set a cover to be closed and test it, if the cover is already closed the cover opens. It should send the close command, not the open command. I don't get it.

## Steps to reproduce

Have a template cover set as the example config above and Homebridge installed. Pair with Home app and try to control it using the Home App.

## Proposed changes

Not sure if this is problem on this addon or homebridge core. Not sure what to do, sorry. Optimistic mode has something to do with, since I don't have a sensor to get the cover position.

Thank you very much @frenck! Sorry to bother you.
