### ISSUE TITLE
Cover command broken

### ISSUE THREAD

**Issue by ASchneiderBR** [hassio-addons/addon-homebridge#58]
# Problem/Motivation

Wrong command is sent to open/close cover. This problem was solved on version 2.1.0 and now broken again with version 2.1.1. I’m using a template cover with open and close commands and optimistic mode on. 

## Expected behavior

When a cover is closed on Home app, the close cover service should be sent to HA. Like this log:
`[2017-10-31 13:57:02] [HomeAssistant] Calling service open_cover on Casa`

## Actual behavior

According to the log, the command `[2017-10-31 13:22:19] [HomeAssistant] Setting the state of the Sala to 0` is sent to HA. Nothing happens. The position is set to 0 but the close cover service is not started. 

## Steps to reproduce

Have a template cover with optimistic mode on on HA and configured with the Home App. 

## Proposed changes

As seen on previous version logs, it should send the close_cover service.

**Comment by ASchneiderBR** [comment]
Hello @frenck, sorry to bother you again my friend :)

I have a garage door set as template cover as well. When I open it, the log shows:

`[2017-10-31 13:57:02] [HomeAssistant] Calling service open_cover on Casa
`

It works like a charm. I am investigating what is going on.

**Comment by ASchneiderBR** [comment]
This is my config:

```
cover:
  - platform: template
    covers:
      persiana_sala: # Not Working
        optimistic: true
        friendly_name: "Persiana da sala"
        stop_cover:
          service: script.persiana_sala_parar
        open_cover:
          service: script.persiana_sala_abrir
        close_cover:
          service: script.persiana_sala_fechar
      garagem_casa: # Working
        optimistic: true
        open_cover:
          service: script.garagem_casa_abrir
        close_cover:
          service: script.garagem_casa_fechar
        friendly_name: "Garagem de casa"
```
The only difference is the stop cover command that I use on HA GUI...
